#!/usr/bin/env bash
AMP=0.025
SIZE=20

FREQUENCIES="20 30 40 60 80 100 120 140"
FOLDER='../standard_size20_amp25'
if [ $1 ]; then
	FOLDER=$1
	echo "Saving to folder "$FOLDER
	if [ ! -d "$FOLDER" ]; then
		mkdir $FOLDER
	fi
fi

for F in `echo $FREQUENCIES`
do
	echo "Running phase response curve for "$F"Hz."
	./prc.py -s $SIZE -a $AMP -f $F -g $FOLDER"/prc_"$F"Hz.h5"
done

