#!/bin/bash
  # choose queue: qshort (1h), qreg (24h), qlong (72h), qxlong (168h)
#PBS -q qreg

#PBS -N NAME

#PBS -l walltime=24:00:00

#PBS -l nodes=1

# #PBS -W x=nmatchpolicy:exactnode
# #PBS -l naccesspolicy=singlejob
# #PBS -l advres=tier1-test.11124

#PBS -m e
#PBS -M joao@tnb.ua.ac.be

#PBS -o DIRECTORY0/NAME.o
#PBS -e DIRECTORY0/NAME.e


export JOBDIR=DIRECTORY0
export SCRIPTDIR=DIRECTORY1

cd $SCRIPTDIR  # so that the mechanisms are loaded properly

module purge
module load NEURON
module load HDF5

echo `date` " - Started job - " hostname
nrniv -python HFS_fibers.py $JOBDIR/MODELCFG
echo `date` " - end Job"

