COMMENT

   **************************************************
   File generated by: neuroConstruct v1.6.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   cad (Type: Ion concentration, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = SI Units 
   /channelml/ion/@name = ca 
   /channelml/ion/@charge = 2 
   /channelml/ion/@role = SignallingSubstance 
   /channelml/ion/notes = Signifies that the ion is involved in a process which alters its concentration 
   /channelml/ion_concentration/@name = cad 
   /channelml/ion_concentration/status/@value = in_progress 
   /channelml/ion_concentration/status/comment = Due to different num integration method in orig mod a dt of 0.002 is needed for very close agreement 
   /channelml/ion_concentration/status/contributor/name = Padraig Gleeson 
   /channelml/ion_concentration/notes = An expontially decaying pool of calcium 
   /channelml/ion_concentration/authorList/modelAuthor[1]/name = De Schutter, E. 
   /channelml/ion_concentration/authorList/modelAuthor[2]/name = Bower, J. 
   /channelml/ion_concentration/authorList/modelTranslator[1]/name = Padraig Gleeson 
   /channelml/ion_concentration/authorList/modelTranslator[1]/institution = UCL 
   /channelml/ion_concentration/authorList/modelTranslator[1]/email = p.gleeson - at - ucl.ac.uk 
   /channelml/ion_concentration/authorList/modelTranslator[2]/name = Jenny Davie 
   /channelml/ion_concentration/authorList/modelTranslator[2]/institution = UCL 
   /channelml/ion_concentration/authorList/modelTranslator[2]/comment = Conversion of GENESIS model to NEURON 
   /channelml/ion_concentration/authorList/modelTranslator[3]/name = Arnd Roth 
   /channelml/ion_concentration/authorList/modelTranslator[3]/institution = UCL 
   /channelml/ion_concentration/authorList/modelTranslator[3]/comment = Conversion of GENESIS model to NEURON 
   /channelml/ion_concentration/authorList/modelTranslator[4]/name = Volker Steuber 
   /channelml/ion_concentration/authorList/modelTranslator[4]/institution = UCL 
   /channelml/ion_concentration/authorList/modelTranslator[4]/comment = Conversion of GENESIS model to NEURON 
   /channelml/ion_concentration/authorList/modelTranslator[5]/name = Michael Hausser 
   /channelml/ion_concentration/authorList/modelTranslator[5]/institution = UCL 
   /channelml/ion_concentration/authorList/modelTranslator[5]/comment = Conversion of GENESIS model to NEURON 
   /channelml/ion_concentration/publication/fullTitle = De Schutter, E., and Bower, J. M. (1994). An active membrane model of the cerebellar Purkinje cell. I. Simulation of current clamps in slice. J Neurop ... 
   /channelml/ion_concentration/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=pubmed&amp;cmd=Retrieve&amp;dopt=AbstractPlus&amp;list_uids=7512629 
   /channelml/ion_concentration/ion_species = ca 
   /channelml/ion_concentration/decaying_pool_model/resting_conc = 4e-5 
   /channelml/ion_concentration/decaying_pool_model/decay_constant = 1e-4 
   /channelml/ion_concentration/decaying_pool_model/fixed_pool_info/phi = 0.259083466 

// File from which this was generated: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/cad/CaPool.xml

// XSL file with mapping to simulator: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/cad/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: SI Units

    

? Creating ion concentration

TITLE Channel: cad

COMMENT
    An expontially decaying pool of calcium
ENDCOMMENT


UNITS {
    (mV) = (millivolt)
    (mA) = (milliamp)
    (um) = (micrometer)
    (l) = (liter)
    (molar) = (1/liter)
    (mM) = (millimolar)
}

    
NEURON {
    SUFFIX cad
    USEION ca READ ica WRITE cai VALENCE 2
    
    RANGE cai
    
    RANGE rest_conc
    
    
    RANGE tau
    
    
    GLOBAL total_current
    
    
    RANGE phi
    
    
}

ASSIGNED {

    ica (mA/cm2)
    diam (um)
}

INITIAL {
    cai = rest_conc

}

PARAMETER {

    total_current
    rest_conc = 0.00004 (mM)
          
    
    tau = 0.1 (ms)
   
    phi = 0.259083466
    
}

STATE {

    cai (mM)

}

BREAKPOINT {

    SOLVE conc METHOD derivimplicit
    

}

DERIVATIVE conc {
    cai' = - (phi * ica) - ((cai - rest_conc)/tau)
    

}

