COMMENT

   **************************************************
   File generated by: neuroConstruct v1.6.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   Kdr (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single Channel from De Schutter and Bower 1998 
   /channelml/ion/@name = k 
   /channelml/ion/@charge = 1 
   /channelml/ion/@default_erev = -85 
   /channelml/channel_type/@name = Kdr 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/status/@value = stable 
   /channelml/channel_type/status/comment = Agreement of generated NEURON to original NEURON mod. Agreement on GENESIS when v1.7.1 XSL is used 
   /channelml/channel_type/status/contributor/name = Padraig Gleeson 
   /channelml/channel_type/notes = Delayed rectifier type K current. Based on Roth et al's reimplementation of original GENESIS model in NEURON 
   /channelml/channel_type/authorList/modelAuthor[1]/name = De Schutter, E. 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Bower, J. 
   /channelml/channel_type/authorList/modelTranslator[1]/name = Padraig Gleeson 
   /channelml/channel_type/authorList/modelTranslator[1]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[1]/email = p.gleeson - at - ucl.ac.uk 
   /channelml/channel_type/authorList/modelTranslator[2]/name = Jenny Davie 
   /channelml/channel_type/authorList/modelTranslator[2]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[2]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[3]/name = Arnd Roth 
   /channelml/channel_type/authorList/modelTranslator[3]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[3]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[4]/name = Volker Steuber 
   /channelml/channel_type/authorList/modelTranslator[4]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[4]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[5]/name = Michael Hausser 
   /channelml/channel_type/authorList/modelTranslator[5]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[5]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/publication/fullTitle = De Schutter, E., and Bower, J. M. (1994). An active membrane model of the cerebellar Purkinje cell. I. Simulation of current clamps in slice. J Neurop ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=pubmed&amp;cmd=Retrieve&amp;dopt=AbstractPlus&amp;list_uids=7512629 
   /channelml/channel_type/neuronDBref/modelName = K channels 
   /channelml/channel_type/neuronDBref/uri = http://senselab.med.yale.edu/senselab/NeuronDB/channelGene2.htm#table3 
   /channelml/channel_type/current_voltage_relation/ohmic/@ion = k 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/@default_gmax = 600 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/rate_adjustments/q10_settings/@q10_factor = 3 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/rate_adjustments/q10_settings/@experimental_temp = 37 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/@power = 2 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/@name = m 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[1]/state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/@power = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/@name = h 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate[2]/state/@fraction = 1 
   /channelml/channel_type/hh_gate[1]/@state = m 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/@type = linoid 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/@expr = A*(k*(v-d))/(1 - exp(-(k*(v-d)))) 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@value = 0.282 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@value = 0.08333333 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@value = 8 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/@type = exponential 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/@expr = A*exp(k*(v-d)) 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@value = 5 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@value = -0.0333333 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@value = -127 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/@type = linoid 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/@expr = A*(k*(v-d))/(1 - exp(-(k*(v-d)))) 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[1]/@value = 0.282 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[2]/@value = 0.08333333 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/gamma/parameterised_hh/parameter[3]/@value = -12 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/@type = exponential 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/@expr = A*exp(k*(v-d)) 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[1]/@value = 5 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[2]/@value = -0.0333333 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/zeta/parameterised_hh/parameter[3]/@value = -147 
   /channelml/channel_type/hh_gate[1]/transition/voltage_gate/tau/generic_equation_hh/@expr = 1/(gamma + zeta) 
   /channelml/channel_type/hh_gate[2]/@state = h 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/tau/generic_equation_hh/@expr = v &lt; -25 ? 1200 : 10 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/@type = sigmoid 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/@expr = A/(1 + exp(k*(v-d))) 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[1]/@value = 1 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[2]/@value = 0.25 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate[2]/transition/voltage_gate/inf/parameterised_hh/parameter[3]/@value = -25 
   /channelml/channel_type/impl_prefs/comment = Note, Using the NEURON mod file impl settings to get a closer match 
   /channelml/channel_type/impl_prefs/table_settings/@max_v = 100 
   /channelml/channel_type/impl_prefs/table_settings/@min_v = -100 
   /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 200 

// File from which this was generated: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/Kdr/Kdr_Chan.xml

// XSL file with mapping to simulator: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/Kdr/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single Channel from De Schutter and Bower 1998
ENDCOMMENT

TITLE Channel: Kdr

COMMENT
    Delayed rectifier type K current. Based on Roth et al's reimplementation of original GENESIS model in NEURON
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX Kdr
    USEION k READ ek WRITE ik VALENCE 1 ? reversal potential of ion is read, outgoing current is written
            
    RANGE gmax, gion
    
    RANGE minf, mtau
    RANGE hinf, htau
}

PARAMETER { 
      

    gmax = 0.6 (S/cm2) ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
    
    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
            
    
    gion (S/cm2)
    minf
    mtau (ms)
    hinf
    htau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((1*m)^2)*((1*h)^1)
    ik = gion*(v - ek)
                

}



INITIAL {
    ek = -85
        
    rates(v)
    m = minf
        h = hinf
        
    
}
    
STATE {
    m
    h
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    h' = (hinf - h)/htau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_m, A_alpha_m, k_alpha_m, d_alpha_m, A_beta_m, k_beta_m, d_beta_m, A_gamma_m, k_gamma_m, d_gamma_m, A_zeta_m, k_zeta_m, d_zeta_m, A_tau_m, k_tau_m, d_tau_m, temp_adj_h, A_tau_h, k_tau_h, d_tau_h, A_inf_h, k_inf_h, d_inf_h
        
    TABLE minf, mtau,hinf, htau
 DEPEND celsius
 FROM -100 TO 100 WITH 200
    
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_m = 3^((celsius - 37)/10)     

    temp_adj_h = 3^((celsius - 37)/10)
        
    ?      ***  Adding rate equations for gate: m  ***
        
    ? Found a parameterised form of rate equation for alpha, using expression: A*(k*(v-d)) / (1 - exp(-(k*(v-d))))
    A_alpha_m = 0.282
    k_alpha_m = 0.08333333
    d_alpha_m = 8
     
    
    alpha = A_alpha_m * vtrap((v - d_alpha_m), (1/k_alpha_m))
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp(k*(v-d))
    A_beta_m = 5
    k_beta_m = -0.0333333
    d_beta_m = -127
     
    
    beta = A_beta_m * exp((v - d_beta_m) * k_beta_m)
    
    
    ? Found a parameterised form of rate equation for gamma, using expression: A*(k*(v-d)) / (1 - exp(-(k*(v-d))))
    A_gamma_m = 0.282
    k_gamma_m = 0.08333333
    d_gamma_m = -12
     
    
    gamma = A_gamma_m * vtrap((v - d_gamma_m), (1/k_gamma_m))
    
    
    ? Found a parameterised form of rate equation for zeta, using expression: A*exp(k*(v-d))
    A_zeta_m = 5
    k_zeta_m = -0.0333333
    d_zeta_m = -147
     
    
    zeta = A_zeta_m * exp((v - d_zeta_m) * k_zeta_m)
    
         

    ? Found a generic form of the rate equation for tau, using expression: 1/(gamma + zeta)
                    tau = 1/(gamma + zeta)
        
    mtau = tau/temp_adj_m
    minf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: m ***
    
        
        
    ?      ***  Adding rate equations for gate: h  ***
             

    ? Found a generic form of the rate equation for tau, using expression: v < -25 ? 1200 : 10
                    
    
    if (v < -25 ) {
        tau =  1200 
    } else {
        tau =  10
    }
    htau = tau/temp_adj_h
    
    ? Found a parameterised form of rate equation for inf, using expression: A / (1 + exp(k*(v-d)))
    A_inf_h = 1
    k_inf_h = 0.25
    d_inf_h = -25
     
    
    inf = A_inf_h / (exp((v - d_inf_h) * k_inf_h) + 1)
    
    hinf = inf
          
       
    
    ?     *** Finished rate equations for gate: h ***
    
             

}


? Function to assist with parameterised expressions of type linoid/exp_linear

FUNCTION vtrap(VminV0, B) {
    if (fabs(VminV0/B) < 1e-6) {
    vtrap = (1 + VminV0/B/2)
}else{
    vtrap = (VminV0 / B) /(1 - exp((-1 *VminV0)/B))
    }
}

UNITSON


