COMMENT

   **************************************************
   File generated by: neuroConstruct v1.6.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   NaP (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single Channel from De Schutter and Bower 1998 
   /channelml/ion/@name = na 
   /channelml/ion/@charge = 1 
   /channelml/ion/@default_erev = 45 
   /channelml/channel_type/@name = NaP 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/status/@value = stable 
   /channelml/channel_type/status/comment = Verified equivalence of NEURON and GENESIS mapping to orig NEURON mod impl at 0.02ms dt with current pulse (but 0.002ms is better) 
   /channelml/channel_type/status/issue = Orig NEURON impl had to be 'fixed' to include READ ena for ion, otherwise was using the internally set value of 45 
   /channelml/channel_type/status/contributor/name = Padraig Gleeson 
   /channelml/channel_type/notes = Persistent Na current. Based on Roth et al's reimplementation of original GENESIS model in NEURON 
   /channelml/channel_type/authorList/modelAuthor[1]/name = De Schutter, E. 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Bower, J. 
   /channelml/channel_type/authorList/modelTranslator[1]/name = Padraig Gleeson 
   /channelml/channel_type/authorList/modelTranslator[1]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[1]/email = p.gleeson - at - ucl.ac.uk 
   /channelml/channel_type/authorList/modelTranslator[2]/name = Jenny Davie 
   /channelml/channel_type/authorList/modelTranslator[2]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[2]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[3]/name = Arnd Roth 
   /channelml/channel_type/authorList/modelTranslator[3]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[3]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[4]/name = Volker Steuber 
   /channelml/channel_type/authorList/modelTranslator[4]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[4]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/authorList/modelTranslator[5]/name = Michael Hausser 
   /channelml/channel_type/authorList/modelTranslator[5]/institution = UCL 
   /channelml/channel_type/authorList/modelTranslator[5]/comment = Conversion of GENESIS model to NEURON 
   /channelml/channel_type/publication/fullTitle = De Schutter, E., and Bower, J. M. (1994). An active membrane model of the cerebellar Purkinje cell. I. Simulation of current clamps in slice. J Neurop ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=pubmed&amp;cmd=Retrieve&amp;dopt=AbstractPlus&amp;list_uids=7512629 
   /channelml/channel_type/neuronDBref/modelName = Na channels 
   /channelml/channel_type/neuronDBref/uri = http://senselab.med.yale.edu/senselab/NeuronDB/channelGene2.htm#table2 
   /channelml/channel_type/current_voltage_relation/ohmic/@ion = na 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/@default_gmax = 1 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/rate_adjustments/q10_settings/@q10_factor = 3 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/rate_adjustments/q10_settings/@experimental_temp = 37 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/@power = 3 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/@name = m 
   /channelml/channel_type/current_voltage_relation/ohmic/conductance/gate/state/@fraction = 1 
   /channelml/channel_type/hh_gate/@state = m 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/@type = sigmoid 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/@expr = A/(1 + exp(k*(v-d))) 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[1]/@value = 200 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[2]/@value = -0.0625 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate/transition/voltage_gate/alpha/parameterised_hh/parameter[3]/@value = 18 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/@type = sigmoid 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/@expr = A/(1 + exp(k*(v-d))) 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@name = A 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[1]/@value = 25 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@name = k 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[2]/@value = 0.125 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@name = d 
   /channelml/channel_type/hh_gate/transition/voltage_gate/beta/parameterised_hh/parameter[3]/@value = -58 
   /channelml/channel_type/impl_prefs/comment = Note, Using larger table_divisions. 
   /channelml/channel_type/impl_prefs/table_settings/@max_v = 100 
   /channelml/channel_type/impl_prefs/table_settings/@min_v = -100 
   /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 200 

// File from which this was generated: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/NaP/NaP_Chan.xml

// XSL file with mapping to simulator: /Users/joao/lib/neuron/DSB94-neuroConstruct/neuroConstruct/cellMechanisms/NaP/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single Channel from De Schutter and Bower 1998
ENDCOMMENT

TITLE Channel: NaP

COMMENT
    Persistent Na current. Based on Roth et al's reimplementation of original GENESIS model in NEURON
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX NaP
    USEION na READ ena WRITE ina VALENCE 1 ? reversal potential of ion is read, outgoing current is written
            
    RANGE gmax, gion
    
    RANGE minf, mtau
}

PARAMETER { 
      

    gmax = 0.0010 (S/cm2) ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
    
    ? Reversal potential of na
    ena (mV)
    ? The outward flow of ion: na calculated by rate equations...
    ina (mA/cm2)
            
    
    gion (S/cm2)
    minf
    mtau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((1*m)^3)
    ina = gion*(v - ena)
                

}



INITIAL {
    ena = 45
        
    rates(v)
    m = minf
        
    
}
    
STATE {
    m
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_m, A_alpha_m, k_alpha_m, d_alpha_m, A_beta_m, k_beta_m, d_beta_m
        
    TABLE minf, mtau
 DEPEND celsius
 FROM -100 TO 100 WITH 200
    
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_m = 3^((celsius - 37)/10)
        
    ?      ***  Adding rate equations for gate: m  ***
        
    ? Found a parameterised form of rate equation for alpha, using expression: A / (1 + exp(k*(v-d)))
    A_alpha_m = 200
    k_alpha_m = -0.0625
    d_alpha_m = 18
     
    
    alpha = A_alpha_m / (exp((v - d_alpha_m) * k_alpha_m) + 1)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A / (1 + exp(k*(v-d)))
    A_beta_m = 25
    k_beta_m = 0.125
    d_beta_m = -58
     
    
    beta = A_beta_m / (exp((v - d_beta_m) * k_beta_m) + 1)
    
    mtau = 1/(temp_adj_m*(alpha + beta))
    minf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: m ***
    
             

}


UNITSON


