#!/bin/bash
  # choose queue: qshort (1h), qreg (24h), qlong (72h), qxlong (168h)
#PBS -q QUEUE

#PBS -N NAME

#PBS -l walltime=HH:MM:SS

#PBS -l nodes=NCPUS

#PBS -W x=nmatchpolicy:exactnode
#PBS -l naccesspolicy=singlejob
#PBS -l advres=tier1-test.11124

#PBS -m e
#PBS -M joao@tnb.ua.ac.be

#PBS -o DIRECTORY0/NAME.o
#PBS -e DIRECTORY0/NAME.e


export JOBDIR=DIRECTORY0
export SCRIPTDIR=DIRECTORY1

cd $SCRIPTDIR  # so that the mechanisms are loaded properly

module purge
module load NEURON
module load HDF5
module load mpiexec

n_proc=$(cat $PBS_NODEFILE | wc -l)
n_node=$(cat $PBS_NODEFILE | uniq | wc -l)


echo `date` " - Started job - " hostname
#mpirun -r ssh -genv I_MPI_FABRICS shm:ofa,tcp -genv I_MPI_DAPL_PROVIDER ofa-v2-mlx4_0-1 -genv I_MPI_FALLBACK 1 -n ${n_proc}  nrniv -mpi -python pyr3Traub.py -c $JOBDIR/MODELCFG
mpiexec nrniv -mpi -python pyr3Traub.py -c $JOBDIR/MODELCFG
echo `date` " - end Job"



